### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by katyapavlenko** [beatlabs/delete-old-branches-action#10]
Hi! Please implement flag that would allow to delete only branches that are merged to master (or other branch name)

**Comment by Szasza** [comment]
Hi @katyapavlenko ,

I think this has already been implemented. The inputs support keeping branches intact via `default_branches` and extra_protected_branch_regex`, and you can exclude all branches which have open PR-s using `exclude_open_pr_branches` (which has a default value of `true`).

The only issue I can see is someone having a branch which hasn't been updated for a longer time and doesn't have a PR, which will be dropped if the newest commit's age reaches the threshold.
